services:
  postgres:
    image: postgres:16
    platform: linux/arm64/v8
    container_name: entregasos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: entregasos
      POSTGRES_PASSWORD: entregasos
      POSTGRES_DB: entregasos_dev
    ports:
      - "5432:5432"
    volumes:
      - entregasos_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U entregasos -d entregasos_dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7
    container_name: entregasos-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - entregasos_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  entregasos_pg_data:
  entregasos_mongo_data:
